# .github/workflows/ci.yml
name: Node.js CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Use Node.js 22.17.0
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test